# Generated by Django 4.0.2 on 2022-02-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadimagetest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awsimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
